mypet:
  property: default
server:
  port: 8181
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
        enabled-by-default: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8070/eureka/
